keywords = ['nfl', 
'nba',
'mlb',
'mma',
'nhl',
'draftkings',
'fanduel',
'sportsbook',
'golf',
'pga',
'baseball',
'basketball',
'football',
'hockey',
'sports',
'betting',
'odds',
'giants',
'nyg',
'nyk',
'betting',
'spread',
'moneyline',
'parlay',
'underdog',
'breakeven',
'philadelphia eagles',
'chiefs',
'packers',
'patriots',
'cardinals',
'buccaneers',
'tampa bay buccaneers',
'brady',
'over/under',
'miami dolphins',
'buffalo bills',
'chicago bears',
'49ers',
'san francsisco 49ers',
'lebron james',
'gamenight',
'game night',
'seattle seahawks',
'las vegas raiders',
'new orleans saints',
'denver broncos',
'minnesota vikings',
'washington commanders',
'baltimore ravens',
'carolina panthers',
'detroit lions',
'cincinatti bengals',
'new york jets',
'indianapolic colts',
'los angeles chargers',
'jacksonville jaguars',
'tennessee titans',
'los angeles rams',
'houston texans',
'atlanta falcons',
'dallas cowboys',
'pittsburgh steelers',
'aaron judge',
'mike trout',
'against the spread',
'bookie',
'bookmaker',
'future bet',
'straight bet',
'yards',
'head coach',
'prizepicks',
'barcelona',
'world series',
'super bowl',]